### ISSUE TITLE
Lag in wavemeter readings

### ISSUE THREAD

**Issue by cjbe** [ljstephenson/wand#19]
After running a server+client pair for a while (several days) the wavemeter readings have a large amount of lag. The wavemeter readings continue to update at their normal rate, but can lag the actual laser frequency by up to 10 seconds. 

This has been particularly obvious on the new-lab wavemeter, as it has been left running for a few weeks.

**Comment by ljstephenson** [comment]
Yeah I noticed this today. Unfortunately I think it's something to do with quamash, which I had problems with initially and had to go with a lower data rate, even though the backend worked fine with asyncio. The reason I say unfortunately is that asyncio is pretty deeply relied upon in the code, and I think the only feasible fix is to switch everything to Qt core, which makes it a Pretty Big Job(TM). I want to do this but have no idea about the timeline... The obvious and annoying workaround is to close and reopen the client, which sucks from the user perspective. The server doesn't need to be restarted.

**Comment by ljstephenson** [comment]
Fixed in 2.0, client backend entirely rewritten with basic python threading and sockets
