### ISSUE TITLE
Save settings breaks something

### ISSUE THREAD

**Issue by cjbe** [ljstephenson/wand#5]
If save settings is pressed, then the server craps out and doesn't know what to do afterwards. It does actually save the settings though

**Comment by ljstephenson** [comment]
To save a single channels state the server does the following:
(a) stash the current state for all channels
(b) restore the file state for all channels, then overwrite with the channel to be saved
(c) save current state to file
(d) restore current state from stash

However, when restoring state the channels are reinitialised and lose the information about which clients were connected to them.

Either the server needs to save settings without completely reinitialising itself (the best option) or it should stash the connected clients while saving.

**Comment by ljstephenson** [comment]
Server doesn't mess with the current configuration, just loads a dict and manipulates that before saving it
